bug:
  - '/\bbug\b/i'
  - '/\berror\b/i'
  - '/\bexception\b/i'
  - '/\bcrash\b/i'
feature:
  - '/\bfeature\b/i'
  - '/\brequest\b/i'
  - '/\bimprovement\b/i'
  - '/\benhancement\b/i'
question:
  - '/\bquestion\b/i'
  - '/\bhelp\b/i'
  - '/\bhow to\b/i'
  - '/\bvraag\b/i'
