name: Issue labeler (keywords)

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply labels based on title/body
        uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/issue-labeler.yml
          include-title: 1
          include-body: 1
          enable-versioned-regex: 0
          repo-token: ${{ github.token }}
