name: Issue labeler (keywords)

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Label by regex
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const issue = context.payload.issue;
            const text = `${issue.title}\n\n${issue.body || ''}`;

            const rules = {
              bug: [/\bbug\b/i, /\berror\b/i, /\bexception\b/i, /\bcrash\b/i],
              feature: [/\bfeature\b/i, /\brequest\b/i, /\bimprovement\b/i, /\benhancement\b/i],
              question: [/\bquestion\b/i, /\bhelp\b/i, /\bhow to\b/i, /\bvraag\b/i],
            };

            const toAdd = [];
            for (const [label, patterns] of Object.entries(rules)) {
              if (patterns.some((re) => re.test(text))) toAdd.push(label);
            }

            if (toAdd.length) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: toAdd,
              });
              core.info(`Added labels: ${toAdd.join(', ')}`);
            } else {
              core.info('No labels matched.');
            }
